### ISSUE TITLE
Plugin can not be found for none IntelliJ IDEA

### ISSUE THREAD

**Issue by Wulfklaue** [kingsleyh/DLanguage#123]
Example: CLion, PHPStorm, ...

Currently the plugin forces people to buy the expensive IntelliJ version, while all the alternative versions run the same backend. Other plugins for Rust, Go allow people to run there plugin in most of the specific versions ( all it takes is deactivate the base language plugins ( example: Cm PHP ), and turn into into a Rust/Go/... IDE  ). 

The current artificial limitation forces people into buying the $150 base version ( Jetbrain does not allow discounted upgrading from specific version like C/PHP to the IntelliJ version )

Its one of those D barriers that reduces language adaptation. While Go/Rust/... all are found with ease, for people who own CLion, PHPStorm, ...

**Comment by SjoerdNijboer** [comment]
You can only run this in a payed version? Have you tried community?

**Comment by Wulfklaue** [comment]
The community version lacks features like Remote Deploy. And remote terminal also ( if i remember correctly )... There is a reason why you pay for the full ;)

And currently the 1.10 plugin trows plenty of exceptions.

**Comment by kingsleyh** [comment]
I only use IntelliJ ultimate and don't own the other IntelliJ products so my initial goal was to get a D plugin working on that and then work on supporting other IntelliJ products.

However as you can probably tell from the lack of activity in the code base I've not had any time to work on the plugin - and it's looking unlikely I'll have much time until mid to end of the year.

The plugin is missing a lot of features but I got the impression that only a handful of people are interested in using jet brains products to code D - so getting people to help contribute to this project is not easy. I'd welcome someone else becoming the maintainer so I can step away and become a user instead - but looks like that is not happening - and since I still use the plugin I don't want it to die.

I understand your frustration but I'm not really in a position to do anything about it at the moment. Maybe the plugins for other languages have more people and resources supporting them.

If you want to make a pull request I'll try to merge it in.

**Comment by Wulfklaue** [comment]
From my understanding, the other IDEs are all based upon IntelliJ and beyond the plugins are almost identical.

You may be surprised by the amount of people that fall back on IntelliJ products. A simple example is by looking at Rust IntelliJ plugin. Rust: 72k. Go: 680k. The Go plugin even forced Jetbrain to start developed on there own Go IDE ( See the recent development release of gogland ).

It looks more or less that the D community is simply small and this results in a lack of resources. Its the chicken or the egg issue. Lack community = IDE lagging behind. IDE lagging behind = lack community growth. 

I understand that you do not have the time. Its a issue that plagues us all. I like D but frankly after putting maybe 20+ hours on several IDE/Editors to get them to work right, its beyond frustrating. At best for the known IDE the best working / feature complete are VSC and Vim. All the rest have small to major issues, that involve a lot of time to the end user.

Still deciding between D, Rust or Go. But Rust and Go seem to have the communities to have better IDE support ( from my perspective ). 

But thanks for the work, maybe your work will allow others to pick up.
