### ISSUE TITLE
Ant managed project?

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#61]
Is Ant still a thing? SHould this project be a Gradle one, or at least a Maven one?

**Comment by kingsleyh** [comment]
I'd rather put my current available time into improving the plugin features and since the ant build mostly works It's not high on my list to re-write it. I don't particularly like Maven or Gradle so I'm not very motivated to change it. If someone else wants to convert it and send a pull request I would probably take it.

**Comment by russel** [comment]
That approach/attitude works for me, improving the plugin is the primary thing. I'll look at adding a Gradle build and see if I can convince you about it rather than Ant.
