### ISSUE TITLE
Wiki page with suggestions for contributions

### ISSUE THREAD

**Issue by peanutman** [kingsleyh/DLanguage#98]
I love your work on the IntelliJ plugin for the D language! Out of all the different IDE options I really believe an IntelliJ-based plugin has the most potential in the long run. 

I'm not sure if it's still maintained but it would be great to see it get developed further. Do you have plans to continue work on it, and is the scheduled beta date still valid?

I would be willing to help out but I've never done anything like this before. If you have a suggestion for a simple task that I can try as a first contribution, let me know! Maybe it makes sense to add a wiki page with some tasks that you would like help with (ranked from easy to complex)?

Thanks for the work so far!

**Comment by kingsleyh** [comment]
Hi

Thanks for the kind words! I've been taking a break as I've been really busy with work and stuff. 

I've been talking to Russel Winder who is keen to continue the development of this plugin but focused on CLion instead of IntelliJ. I guess it makes sense as D is closer to C and IntelliJ is more JVM suited.

I'm really not sure if I will do any more work on the plugin this year - if I do I would probably switch to programming in Kotlin and support Russel.

What is your technical background? The plugin is written in Java. If you are keen I could walk you through what I have so far and maybe put you in touch with Russel as well.

--Kingsley

**Comment by SingingBush** [comment]
I'm happy to help with the Kotlin conversion

**Comment by SingingBush** [comment]
Re CLion, Intellij IDEA Ultimate is likely to get the functionality of CLion as a plugin. I've seen a reply from one of the Jet brains guys indicating that anyway. All their IDE's are essentially Intellij anyway. 

Have you seen language server protocol that is going to be used by Eclipse Che and Visual Studio Code? I put money on Her brains supporting it within 12 months

**Comment by kingsleyh** [comment]
We should get together with you, me, peanutman and Russel Winder and see if we can collaborate on something

**Comment by SingingBush** [comment]
just saw that auto spelling correct had changed 'Jetbrains' to 'her brains' in prev comment.  Yeah I'm happy discuss over skype/google hangout/whatever else. Best time for me would be an evening after 8pm (after baby goes to sleep).

**Comment by peanutman** [comment]
Sounds good to me. I have a personal deadline at the end of the week but from next week on I can definitely help. I've never worked with Kotlin or with the plug-in SDK, but I have the technical background to figure it out.

**Comment by kingsleyh** [comment]
Hi - great - ok next week is good for me. Ideally a weekday evening time - 8:30pm UK time or later - why don't you all add me to Skype and we can try to catch up. 

I don't know your location peanutman but I guess everyone else is in the UK

My Skype is: kingsleyh

**Comment by kingsleyh** [comment]
peanutman - whats your skype?
